/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class code_example_jni_CppJni */

#ifndef _Included_code_example_jni_CppJni
#define _Included_code_example_jni_CppJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     code_example_jni_CppJni
 * Method:    random
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_code_example_jni_CppJni_random
  (JNIEnv *, jobject);

/*
 * Class:     code_example_jni_CppJni
 * Method:    add
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_code_example_jni_CppJni_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     code_example_jni_CppJni
 * Method:    sort
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_code_example_jni_CppJni_sort
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     code_example_jni_CppJni
 * Method:    getSimpleMath
 * Signature: ()Lcode/example/jni/SimpleMath;
 */
JNIEXPORT jobject JNICALL Java_code_example_jni_CppJni_getSimpleMath
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
